# Generated by Django 4.1 on 2022-09-04 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_created_at_alter_bid_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 4, 18, 33, 441048)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 4, 18, 33, 441048)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 4, 18, 33, 441048)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 4, 18, 33, 442048)),
        ),
    ]
